before_install:
  - sudo apt-get install -y libgtk-3-dev libepoxy-dev
addons:
  apt:
    update: true
language: rust
rust:
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo
